name: Release

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    environment: PyPI
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/python-poetry-env
      - name: Build package
        run: poetry build --no-interaction
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force
