name: Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.21
        shell: bash
      - name: Check workflow files
        run: ./actionlint -color
        shell: bash

  lint-cruft:
    name: Check if automatic project update was successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if .rej files exist as structure update was not successful
        run: test -z "$(find . -iname '*.rej')"

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry run pytest --cov=src tests --cov-report=xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - run: poetry run mkdocs build

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4.1.8
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
